import React, { useState } from 'react';
import { Printer, Copy, Check, FileText, Activity, Compass, Target, ArrowDown } from 'lucide-react';
import Modal from '../ui/Modal';
import Button from '../ui/Button';

export default function MorningMemoModal({
  isOpen,
  onClose,
  watchlistName = 'Pulse Watchlist',
  feedData,
  healthData
}) {
  const [copied, setCopied] = useState(false);

  if (!feedData) return null;

  const needsAttention = feedData.needsAttention || [];
  const quiet = feedData.quiet || [];
  const allItems = [...needsAttention, ...quiet];
  const currentDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });
  const formattedTime = feedData.lastSuccessfulFetchFormatted || new Date().toLocaleTimeString();

  const handlePrint = () => {
    window.print();
  };

  const handleCopyText = () => {
    const lines = [
      `*PULSE MORNING MEMO — ${watchlistName.toUpperCase()}*`,
      `Date: ${currentDate} | Time: ${formattedTime}`,
      `Market Status: ${feedData.finnhub?.feedSourceLabel || 'Live Feed'}`,
      `Health Score: ${healthData?.overallScore || 85}/100`,
      '',
      `*FLAGGED ATTENTION MOVERS:*`,
      ...needsAttention.slice(0, 3).map(it => 
        `• ${it.ticker} (${it.symbolPrefix || '$'}${it.price}): ${it.pctChangeDay >= 0 ? '+' : ''}${it.pctChangeDay}% | Attention: ${it.attentionScore} | Vol: ${it.scoreBreakdown?.volumeAnomalyRatio || 1}x\n  → ${it.narrative}`
      ),
      '',
      `*QUIET & BALANCED (${quiet.length} STOCKS):*`,
      quiet.slice(0, 4).map(it => it.ticker).join(', ') + (quiet.length > 4 ? ` + ${quiet.length - 4} more` : ''),
      '',
      `Generated by Pulse Triage Watchlist (CODE 2026 Groww Hackathon)`
    ];
    navigator.clipboard.writeText(lines.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Executive Morning Memo (Print / PDF)" maxWidth="max-w-2xl">
      <div className="space-y-4 text-xs">
        {/* Actions Bar */}
        <div className="flex items-center justify-between p-3 rounded-xl bg-slate-900 border border-white/5 no-print">
          <div className="flex items-center gap-2 text-slate-400">
            <FileText className="w-4 h-4 text-teal-400" />
            <span>Formatted for 1-Page PDF Export or Slack Sharing</span>
          </div>

          <div className="flex items-center gap-2">
            <Button variant="secondary" size="sm" onClick={handleCopyText}>
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied Text' : 'Copy Slack Memo'}</span>
            </Button>
            <Button variant="primary" size="sm" onClick={handlePrint}>
              <Printer className="w-3.5 h-3.5" />
              <span>Print to PDF</span>
            </Button>
          </div>
        </div>

        {/* The Printable Document Area */}
        <div id="printable-morning-memo" className="p-6 rounded-2xl bg-slate-950 border border-white/10 space-y-4 text-slate-200">
          {/* Memo Header */}
          <div className="flex items-start justify-between border-b border-white/10 pb-4">
            <div>
              <div className="flex items-center gap-2">
                <div className="w-6 h-6 rounded-lg bg-teal-500 flex items-center justify-center font-black text-slate-950 text-xs">
                  P
                </div>
                <span className="font-black text-base tracking-tight text-white font-mono">
                  PULSE MARKET MEMO
                </span>
              </div>
              <p className="text-xs text-slate-400 mt-1">
                Executive Triage & Risk Briefing • <span className="text-teal-400 font-semibold">{watchlistName}</span>
              </p>
            </div>

            <div className="text-right font-mono text-[11px] text-slate-400">
              <div className="text-white font-bold">{currentDate}</div>
              <div>{formattedTime} • As of Polling Tick</div>
              <div className="text-[10px] text-teal-400 font-bold">CONFIDENTIAL / INTERNAL</div>
            </div>
          </div>

          {/* Quick Metrics Bar */}
          <div className="grid grid-cols-3 gap-2.5 p-3 rounded-xl bg-slate-900/80 border border-white/5 text-center font-mono">
            <div>
              <span className="text-[10px] text-slate-400 uppercase block">Watchlist Health</span>
              <span className="text-base font-bold text-teal-300">
                {healthData?.overallScore || 88}<span className="text-xs text-slate-500">/100</span>
              </span>
            </div>
            <div>
              <span className="text-[10px] text-slate-400 uppercase block">Attention Focus</span>
              <span className="text-base font-bold text-amber-300">
                {needsAttention.length} <span className="text-xs text-slate-400 font-normal">Flagged</span>
              </span>
            </div>
            <div>
              <span className="text-[10px] text-slate-400 uppercase block">Quiet Assets</span>
              <span className="text-base font-bold text-slate-300">
                {quiet.length} <span className="text-xs text-slate-400 font-normal">Suppressed</span>
              </span>
            </div>
          </div>

          {/* Top Flagged Attention Table */}
          <div className="space-y-2">
            <span className="text-[11px] font-mono uppercase tracking-wider text-teal-400 font-bold block">
              Flagged Assets Requiring Today's Attention
            </span>

            <div className="overflow-x-auto">
              <table className="w-full text-left font-mono text-xs border-collapse">
                <thead>
                  <tr className="border-b border-white/10 text-[10px] text-slate-400 uppercase">
                    <th className="pb-1.5">Ticker</th>
                    <th className="pb-1.5">Price</th>
                    <th className="pb-1.5">Move</th>
                    <th className="pb-1.5">Vol Surge</th>
                    <th className="pb-1.5">Score</th>
                    <th className="pb-1.5">Primary Driver</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {needsAttention.map((it) => (
                    <tr key={it.ticker} className="hover:bg-white/5">
                      <td className="py-2 font-bold text-white">{it.ticker}</td>
                      <td className="py-2">
                        {it.symbolPrefix || '$'}{it.price}
                      </td>
                      <td className={`py-2 font-bold ${it.pctChangeDay >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                        {it.pctChangeDay >= 0 ? '+' : ''}{it.pctChangeDay}%
                      </td>
                      <td className="py-2 text-slate-300">
                        {it.scoreBreakdown?.volumeAnomalyRatio || 1}x
                      </td>
                      <td className="py-2 text-teal-300 font-bold">
                        {it.attentionScore}
                      </td>
                      <td className="py-2 text-slate-300 text-[11px] font-sans truncate max-w-[200px]">
                        {it.catalysts?.[0]?.headline || it.narrative}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Quiet Stocks Summary */}
          {quiet.length > 0 && (
            <div className="pt-2 border-t border-white/5 flex items-center justify-between text-[11px] text-slate-400 font-mono">
              <span>Quiet / Controlled Regime:</span>
              <span className="text-slate-300">
                {quiet.map(q => q.ticker).join(' • ')}
              </span>
            </div>
          )}

          {/* Footer */}
          <div className="pt-3 border-t border-white/10 flex items-center justify-between text-[10px] text-slate-500 font-mono">
            <span>Pulse Triage System • Groww CODE 2026 Submission</span>
            <span>https://pulse.market</span>
          </div>
        </div>
      </div>
    </Modal>
  );
}
